# Generated by Django 3.0.6 on 2020-06-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invent',
            name='state',
            field=models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], default='active', max_length=50),
        ),
    ]
