# Generated by Django 3.0.6 on 2020-05-31 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users_app.utils.helpers
import users_app.utils.id_genrator


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.CharField(default=users_app.utils.id_genrator.generate_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invent',
            fields=[
                ('id', models.CharField(default=users_app.utils.id_genrator.generate_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('about_invention', models.TextField(default='About your invention and possibly links to it', null=True)),
                ('invent_media', models.URLField()),
                ('state', models.CharField(choices=[(users_app.utils.helpers.StateType['active'], 'active'), (users_app.utils.helpers.StateType['deleted'], 'deleted')], default=users_app.utils.helpers.StateType['active'], max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
