language: python
python:
  - "3.8"
install:
  - pip install pipenv
  - pipenv install
services:
  - postgresql
before_script:
  - "psql -c 'create database elitedb;' -U postgres"
  - make migrate
script:
  - make test