# Generated by Django 3.0.6 on 2020-06-06 11:14

from django.db import migrations, models
import utils.id_genrator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.CharField(default=utils.id_genrator.generate_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('rejected', 'rejected')], default='pending', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
